# Generated by Django 6.0.3 on 2026-08-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('grade', models.CharField(default='Class 3', max_length=50)),
                ('subject', models.CharField(default='Science', max_length=100)),
                ('lang', models.CharField(default='Odia', max_length=50)),
                ('status', models.CharField(default='Ready', max_length=50)),
                ('num_chunks', models.IntegerField(default=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='LessonRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Lesson', max_length=255)),
                ('grade', models.CharField(default='Class 3', max_length=50)),
                ('subject', models.CharField(default='Science', max_length=100)),
                ('source_lang', models.CharField(default='English', max_length=50)),
                ('target_lang', models.CharField(default='Odia', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='QuizResultRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='Water Cycle', max_length=255)),
                ('score', models.IntegerField(default=3)),
                ('total', models.IntegerField(default=3)),
                ('percentage', models.FloatField(default=100.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quiz_results',
            },
        ),
    ]
