# Generated by Django 5.2.12 on 2026-09-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrecord',
            name='direct_translation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lessonrecord',
            name='example',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lessonrecord',
            name='key_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lessonrecord',
            name='learner_question',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lessonrecord',
            name='pedagogical_adaptation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lessonrecord',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
    ]
