# Generated by Django 5.2.12 on 2026-09-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_lessonrecord_direct_translation_lessonrecord_example_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrecord',
            name='qa_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
